use diskburrow_services::AppSettings;
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Page {
    Overview,
    Largest,
    Map,
    History,
    Cleanup,
    Settings,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Setting {
    Interval,
    LowSpaceGb,
    GrowthGb,
    Language,
    Theme,
    UiScale,
    MapDepth,
    ShowHidden,
    SidebarWidth,
    Battery,
    Autostart,
    Exclusions,
    CustomTemp,
}
#[derive(Clone, Debug)]
pub enum Command {
    SetRoot(String),
    Scan(bool),
    Cancel,
    Pause,
    SaveSettings,
    Setting(Setting, String),
    Mark(String),
    PreviewManual,
    ConfirmManual,
    DismissReview,
    AnalyzeCleanup,
    ToggleCandidate(String),
    CleanupFilter(String),
    CleanupCategory(String),
    ExcludeCandidate(String),
    ExcludeCategory,
    PreviewCleanup,
    ConfirmCleanup,
    SelectHistory(String),
    Export(String),
    ExportSelection(String),
    ClearMarks,
    MapWiden(String),
    MapColor(u8),
    MapNavigate(usize),
    MapBack,
    MapForward,
    MapUp,
    MapRoot,
    MapFocus(usize),
    MapMark(usize),
    MapSearch(String),
    MapIsolate(bool),
    MapGlobal(bool),
    MapMetric(u8),
    MapZoom(f32),
    Open(String),
    Maintenance(usize),
    Exit,
}
#[derive(Clone, Debug, Default)]
pub struct Row {
    pub key: String,
    pub path: String,
    pub selected: bool,
    pub selectable: bool,
    pub cells: Vec<String>,
}
#[derive(Clone, Debug)]
pub struct MapTile {
    pub index: usize,
    pub name: String,
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    pub directory: bool,
    pub marked: bool,
    pub covered: bool,
    pub matched: bool,
    pub depth: u32,
    pub category: u8,
    pub reclaim: bool,
    pub age: u8,
}
#[derive(Clone, Debug, Default)]
pub struct Review {
    pub id: String,
    pub title: String,
    pub summary: String,
    pub warnings: Vec<String>,
    pub rows: Vec<Row>,
    pub can_confirm: bool,
    pub cleanup: bool,
}
#[derive(Clone, Debug)]
pub struct UiView {
    pub settings: AppSettings,
    pub root: String,
    pub busy: bool,
    pub paused: bool,
    pub status: String,
    pub error: Option<String>,
    pub overview: Vec<(String, String)>,
    pub volume_stamp: String,
    pub issue_rows: Vec<Row>,
    pub folders: Vec<Row>,
    pub files: Vec<Row>,
    pub history: Vec<Row>,
    pub changes: Vec<Row>,
    pub history_heading: String,
    pub cleanup: Vec<Row>,
    pub cleanup_warnings: Vec<Row>,
    pub cleanup_results: Vec<Row>,
    pub observed_caches: Vec<Row>,
    pub recommendations: Vec<Row>,
    pub cleanup_summary: String,
    pub cleanup_categories: Vec<String>,
    pub cleanup_category: String,
    pub review: Option<Review>,
    pub selected_count: usize,
    pub map_path: String,
    pub map_breadcrumbs: Vec<(usize, String)>,
    pub map_parents: Vec<(String, String)>,
    pub map_visible_summary: String,
    pub scan_reuse_notice: String,
    pub map_objects: Vec<Row>,
    pub map_matches: usize,
    pub map_query: String,
    pub map_global: bool,
    pub map_isolate: bool,
    pub map_metric: u8,
    pub map_color: u8,
    pub map_zoom: f32,
    pub map_has_data: bool,
    pub focused_path: String,
    pub focused_summary: String,
    pub git_summary: String,
    pub drives: Vec<(String, String)>,
    pub can_cleanup: bool,
    pub can_manual: bool,
}
